fix(audit): incorrect audit report redirect params
aexvir/the-zoo pull request #382
Opened 2021-02-24 09:42 UTC by jarosevcik

2021-02-24 09:44 UTC, aexvir commented
Please let's make sure this is covered by tests 🙂️
Right now it was broken and we didn't have any failing test because of it

2021-02-24 09:58 UTC, batisteo commented
And I guess those lines have to be deleted :confused: 
https://github.com/kiwicom/the-zoo/blob/master/.github/workflows/push.yml#L64-L65

2021-02-26 12:41 UTC, aexvir requested changes

2021-02-26 12:41 UTC, aexvir commented on test/auditing/test_views.py
> +def test_url_resolution(client, user, service_factory):
hmm... this seems to be testing django's native `reverse` function, which is probably already tested by django itself 😅️

what I'd test here is that during the execution of `notify_status_change` there is a call to `reverse` with the correct attributes

e.g.
```python
m_reverse.assert_called_once_with('service', service.owner_slug, service.name_slug)
```

2021-02-26 14:31 UTC, batisteo approved these changes
Looks good

2021-02-26 14:32 UTC, merged